### ISSUE TITLE
SSL Certs

### ISSUE THREAD

**Issue by RobThree** [ben174/hsts-cookie#1]
> TODO: I need a wildcard SSL cert ($$$) to host a live demo. 

Can't you simply add 24 (or whatever amount of subdomains) [free SSL certs](https://letsencrypt.org/)? For each subdomain one?

**Comment by RobThree** [comment]
Ah [missed this one](https://www.reddit.com/r/programming/comments/40t23i/hsts_super_cookie_can_fingerprint_your_browser/) :wink: :+1:

**Comment by AlexanderS** [comment]
You can also use one Certificate with multiple SubjectAltNames. If it is only a bounded (letsencrypt currently has a limit of 100 SAN per certificate) set of subdomains there is no need for a wildcard certificate.

**Comment by ben174** [comment]
Thanks @AlexanderS I'll pursue the SubjectAtNames route. Seems like the proper way to go.
